# Generated by Django 2.2.6 on 2020-01-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECOMProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField()),
                ('image_link', models.URLField()),
                ('mobile_link', models.URLField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('in stock', 'In Stock'), ('out of stock', 'Out of Stock'), ('preorder', 'Pre-order')], max_length=255)),
                ('availability_date', models.DateTimeField(max_length=25, null=True)),
                ('cost_of_goods_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expiration_date', models.DateTimeField(max_length=25, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price_effective_date', models.DateTimeField(blank=True, max_length=25, null=True)),
                ('unit_pricing_measure', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_pricing_base_measure', models.CharField(blank=True, max_length=255, null=True)),
                ('installment', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('loyalty_points', models.CharField(blank=True, max_length=255, null=True)),
                ('google_product_category', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(max_length=70)),
                ('gtin', models.CharField(max_length=255)),
                ('MPN', models.CharField(blank=True, max_length=70, null=True)),
                ('identifier_exists', models.CharField(choices=[('yes', 'yes'), ('no', 'No')], max_length=3)),
                ('condition', models.CharField(choices=[('new', 'NewCondition'), ('refurbished', 'RefurbishedCondition'), ('used', 'UsedCondition')], max_length=255)),
                ('adult', models.CharField(choices=[('yes', 'yes'), ('no', 'No')], max_length=3)),
                ('multipack', models.IntegerField(default=0)),
                ('is_bundle', models.CharField(choices=[('yes', 'yes'), ('no', 'No')], max_length=3)),
                ('energy_efficiency_class', models.CharField(choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=255)),
                ('min_energy_efficiency_class', models.CharField(choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=255)),
                ('max_energy_efficiency_class', models.CharField(choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=255)),
                ('age_group', models.CharField(blank=True, choices=[('newborn', 'Up to 3 months old'), ('infant', '3-12 months old'), ('toddler', '1-5 years old'), ('kids', '5-13 years old'), ('adult', 'Older than 13')], max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=255)),
                ('material', models.CharField(max_length=200)),
                ('pattern', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('size_type', models.CharField(blank=True, choices=[('regular', 'Regular'), ('petite', 'Petite'), ('plus', 'Plus'), ('big and tall', 'Big and Tall'), ('maternity', 'Maternity')], max_length=100, null=True)),
                ('size_system', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=255)),
                ('item_group_id', models.CharField(max_length=50)),
                ('adwords_redirect', models.URLField(blank=True, max_length=2000, null=True)),
                ('custom_label_0', models.CharField(blank=True, max_length=100, null=True)),
                ('promotion_id', models.CharField(blank=True, max_length=50, null=True)),
                ('excluded_destination', models.CharField(blank=True, choices=[('Shopping Ads', 'Shopping Ads'), ('Shopping Actions', 'Shopping Actions'), ('Display Ads', 'Display Ads'), ('Surface across Google', 'Surface across Google')], max_length=255, null=True)),
                ('included_destination', models.CharField(blank=True, choices=[('Shopping Ads', 'Shopping Ads'), ('Shopping Actions', 'Shopping Actions'), ('Display Ads', 'Display Ads'), ('Surface across Google', 'Surface across Google')], max_length=255, null=True)),
                ('shipping', models.CharField(max_length=255)),
                ('shipping_label', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_length', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_width', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_height', models.CharField(blank=True, max_length=255, null=True)),
                ('transit_time_label', models.CharField(blank=True, max_length=100, null=True)),
                ('max_handling_time', models.CharField(blank=True, max_length=255, null=True)),
                ('min_handling_time', models.IntegerField(null=True)),
                ('tax', models.CharField(max_length=255)),
                ('tax_category', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_product', to='assembly.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ECOMProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_link', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_image_link', to='eCommerce.ECOMProduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
