# Generated by Django 2.2.6 on 2019-10-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0003_ecomproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomproduct',
            name='multipack',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
