# Generated by Django 2.2.6 on 2019-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0005_auto_20191018_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomproduct',
            name='availability_date',
            field=models.DateTimeField(max_length=25, null=True),
        ),
    ]
