# Generated by Django 2.2.6 on 2019-10-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0006_auto_20191018_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomproduct',
            name='expiration_date',
            field=models.DateTimeField(max_length=25, null=True),
        ),
    ]
