# Generated by Django 2.2.6 on 2019-10-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0007_auto_20191018_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomproduct',
            name='min_handling_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ecomproduct',
            name='sale_price_effective_date',
            field=models.DateTimeField(max_length=25, null=True),
        ),
    ]
