# Generated by Django 2.2.6 on 2019-10-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0008_auto_20191018_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomproduct',
            name='sale_price_effective_date',
            field=models.DateTimeField(blank=True, max_length=25, null=True),
        ),
    ]
