image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: ci

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements.txt

test:
  script:
  - python manage.py test

