# Generated by Django 2.2.4 on 2019-09-03 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PistonComponent',
            fields=[
                ('atomiccomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.AtomicComponent')),
                ('c_type', models.CharField(choices=[('Piston', 'Piston'), ('Tube', 'Tube'), ('Rod', 'Rod'), ('Inner', 'Inner'), ('Rod_Component', 'Rod_Component'), ('Component', 'Component'), ('Endfitting', 'Endfitting'), ('Valve_Block', 'Valve_Block'), ('Spacer', 'Spacer'), ('Sleeve', 'Sleeve'), ('Inner_Tube', 'Inner_Tube'), ('End_Block', 'End_Block'), ('CNC_Component', 'CNC_Component'), ('Ratio_Pseudo', 'Ratio_Pseudo')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('shop.atomiccomponent',),
        ),
    ]
