# Generated by Django 2.2.6 on 2019-10-09 10:02
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atomic', '0001_initial'),
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='group.Group')),
                ('members', models.ManyToManyField(related_name='members', to='assembly.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('group.group',),
        ),
        migrations.CreateModel(
            name='BlueprintGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='group.Group')),
                ('members', models.ManyToManyField(related_name='members', to='assembly.Blueprint')),
            ],
            options={
                'abstract': False,
            },
            bases=('group.group',),
        ),
        migrations.CreateModel(
            name='AtomicGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='group.Group')),
                ('members', models.ManyToManyField(related_name='members', to='atomic.AtomicComponent')),
            ],
            options={
                'abstract': False,
            },
            bases=('group.group',),
        ),
    ]
