# Generated by Django 2.2.6 on 2020-01-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description_images',
            field=models.ManyToManyField(related_name='group_description_images', to='shop.URL'),
        ),
        migrations.AddField(
            model_name='group',
            name='illustration_images',
            field=models.ManyToManyField(related_name='group_illustration_images', to='shop.OffsetImageURL'),
        ),
        migrations.AddField(
            model_name='group',
            name='thumbnail_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_thumbnail_images', to='shop.URL'),
        ),
    ]
