# Generated by Django 2.2.6 on 2019-10-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0002_auto_20191021_1620'),
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyValueAttribute',
            new_name='Attribute',
        ),
    ]
