# Generated by Django 2.2.6 on 2019-11-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuratorstep',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
