# Generated by Django 2.2.6 on 2020-01-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_configuratorstep_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuratorstep',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
