# Generated by Django 2.2.5 on 2019-09-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0002_auto_20190906_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='atomic_prerequisites',
            field=models.ManyToManyField(related_name='atomic_requirements', to='concept.AtomicPrerequisite'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='blueprint_prerequisites',
            field=models.ManyToManyField(related_name='blueprint_requirements', to='concept.BlueprintPrerequisite'),
        ),
    ]
