# Generated by Django 2.2.5 on 2019-09-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atomic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('atomic_prerequisites', models.ManyToManyField(related_name='atomic_requirements', to='atomic.AtomicPrerequisite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('sku', models.CharField(max_length=3)),
                ('availability', models.IntegerField(default=0)),
                ('atomic_specifications', models.ManyToManyField(related_name='atomic_specification', to='atomic.AtomicSpecification')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='based_on', to='assembly.Blueprint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildPrerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('max_quantity', models.PositiveIntegerField(default=1)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requires', to='assembly.Build')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('blueprint_prereq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='build_with', to='assembly.BuildPrerequisite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='build',
            name='build_specifications',
            field=models.ManyToManyField(related_name='build_specification', to='assembly.BuildSpecification'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='build_prerequisites',
            field=models.ManyToManyField(related_name='blueprint_requirements', to='assembly.BuildPrerequisite'),
        ),
    ]
