# Generated by Django 2.2.6 on 2019-10-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atomic', '0001_initial'),
        ('relations', '0001_initial'),
        ('group', '0001_initial'),
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('atomic_prerequisites', models.ManyToManyField(related_name='atomic_requirements', to='atomic.AtomicPrerequisite')),
                ('attribute', models.ManyToManyField(related_name='blueprint_attr', to='attribute.Attribute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('sku', models.CharField(max_length=3)),
                ('availability', models.IntegerField(default=0)),
                ('atomic_specifications', models.ManyToManyField(related_name='atomic_specification', to='atomic.AtomicSpecification')),
                ('attribute', models.ManyToManyField(related_name='product_attr', to='attribute.Attribute')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='based_on', to='assembly.Blueprint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='group.Group')),
                ('members', models.ManyToManyField(related_name='members', to='assembly.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('group.group',),
        ),
        migrations.CreateModel(
            name='ProductPrerequisite',
            fields=[
                ('prerequisite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.Prerequisite')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requires', to='assembly.Product')),
                ('product_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowed_group', to='assembly.ProductGroup')),
            ],
            options={
                'abstract': False,
            },
            bases=('relations.prerequisite',),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('specification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.Specification')),
                ('prerequisite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='build_with', to='assembly.ProductPrerequisite')),
                ('selected_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='using', to='assembly.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('relations.specification',),
        ),
        migrations.AddField(
            model_name='product',
            name='product_specifications',
            field=models.ManyToManyField(related_name='product_specification', to='assembly.ProductSpecification'),
        ),
        migrations.CreateModel(
            name='BlueprintGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='group.Group')),
                ('members', models.ManyToManyField(related_name='members', to='assembly.Blueprint')),
            ],
            options={
                'abstract': False,
            },
            bases=('group.group',),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='product_prerequisites',
            field=models.ManyToManyField(related_name='blueprint_requirements', to='assembly.ProductPrerequisite'),
        ),
    ]
