# Generated by Django 2.2.6 on 2019-10-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprerequisite',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
