# Generated by Django 2.2.5 on 2019-09-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildspecification',
            old_name='blueprint_prereq',
            new_name='build_prereq',
        ),
    ]
