# Generated by Django 2.2.6 on 2019-10-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='keyvalueattribute_ptr',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.DeleteModel(
            name='BlueprintAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
