# Generated by Django 2.2.6 on 2019-10-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='product_prereq',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='prerequisite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='build_with', to='assembly.ProductPrerequisite'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='selected_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='using', to='assembly.Product'),
        ),
    ]
