# Generated by Django 2.2.5 on 2019-09-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='blueprint_specifications',
            new_name='build_specifications',
        ),
    ]
