# Generated by Django 2.2.5 on 2019-10-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_blueprintattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprerequisite',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
