# Generated by Django 2.2.6 on 2019-10-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_auto_20191025_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprerequisite',
            name='virtual',
        ),
    ]
