# Generated by Django 2.2.6 on 2019-11-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_blueprintattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprint',
            name='attribute',
        ),
    ]
