# Generated by Django 2.2.6 on 2019-10-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_auto_20191017_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprerequisite',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowed_group', to='assembly.ProductGroup'),
        ),
        migrations.AlterField(
            model_name='productprerequisite',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requires', to='assembly.Product'),
        ),
    ]
