# Generated by Django 2.2.6 on 2019-11-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_product_component_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='component_factor',
            field=models.FloatField(default=None, null=True),
        ),
    ]
