# Generated by Django 2.2.5 on 2019-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_auto_20190909_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build_specifications',
            field=models.ManyToManyField(related_name='specifications', to='assembly.Build'),
        ),
    ]
