# Generated by Django 2.2.6 on 2020-01-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_auto_20191129_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='component_factor',
            field=models.FloatField(default=None, null=True),
        ),
    ]
