# Generated by Django 2.2.6 on 2020-01-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_blueprint_component_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='build_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
