# Generated by Django 2.2.6 on 2019-11-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OffsetImageURL',
            fields=[
                ('url_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.URL')),
                ('position', models.IntegerField(default=0)),
                ('offset_x', models.IntegerField(default=0, help_text='Image offset x direction')),
                ('offset_y', models.IntegerField(default=0, help_text='Image offset y direction')),
            ],
            options={
                'abstract': False,
            },
            bases=('shop.url',),
        ),
    ]
