# Generated by Django 2.2.6 on 2019-11-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offsetimageurl',
            name='position',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
