# Generated by Django 2.2.5 on 2019-09-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtomAttribute',
            new_name='AtomicAttribute',
        ),
        migrations.RemoveField(
            model_name='atomicattribute',
            name='blueprint',
        ),
        migrations.AddField(
            model_name='atomicattribute',
            name='atomic_component',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='atom_attribute', to='atomic.AtomicComponent'),
            preserve_default=False,
        ),
    ]
