# Generated by Django 2.2.5 on 2019-09-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190927_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprintattribute',
            name='blueprint',
        ),
        migrations.DeleteModel(
            name='AtomicAttribute',
        ),
        migrations.DeleteModel(
            name='BlueprintAttribute',
        ),
    ]
