# Generated by Django 2.2.6 on 2019-11-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_offsetimageurl_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offsetimageurl',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
