# Generated by Django 2.2.6 on 2019-10-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicprerequisite',
            name='atomic_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowed_group', to='atomic.AtomicGroup'),
        ),
        migrations.AlterField(
            model_name='atomicprerequisite',
            name='atomic_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requires', to='atomic.AtomicComponent'),
        ),
    ]
