# Generated by Django 2.2.5 on 2019-10-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atomiccomponent',
            name='part_code',
        ),
        migrations.AddField(
            model_name='atomiccomponent',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
