# Generated by Django 2.2.5 on 2019-10-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomiccomponent',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
