# Generated by Django 2.2.5 on 2019-09-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtomicAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('atomic_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atom_attribute', to='atomic.AtomicComponent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
