# Generated by Django 2.2.6 on 2019-11-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomiccomponent',
            name='component_factor',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
