# Generated by Django 2.2.6 on 2019-11-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191113_2232'),
        ('atomic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atomiccomponent',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='atomiccomponent',
            name='offset_image_urls',
        ),
        migrations.AddField(
            model_name='atomiccomponent',
            name='description_images',
            field=models.ManyToManyField(related_name='description_image', to='shop.URL'),
        ),
        migrations.AddField(
            model_name='atomiccomponent',
            name='illustration_images',
            field=models.ManyToManyField(related_name='illustration_image', to='shop.OffsetImageURL'),
        ),
        migrations.AddField(
            model_name='atomiccomponent',
            name='thumbnail_images',
            field=models.ManyToManyField(related_name='thumbnail_image', to='shop.URL'),
        ),
    ]
