# Generated by Django 2.2.6 on 2019-11-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0002_atomiccomponent_component_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomiccomponent',
            name='component_factor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
