# Generated by Django 2.2.5 on 2019-10-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0002_atomicattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomiccomponent',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
