# Generated by Django 2.2.5 on 2019-10-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0002_auto_20191008_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atomiccomponent',
            old_name='type',
            new_name='category',
        ),
    ]
