# Generated by Django 2.2.6 on 2019-10-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0002_auto_20191016_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicspecification',
            name='selected_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='using', to='atomic.AtomicComponent'),
        ),
    ]
