# Generated by Django 2.2.6 on 2019-10-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0003_atomicspecification_selected_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atomicspecification',
            old_name='atomic_prereq',
            new_name='prerequisite',
        ),
    ]
