# Generated by Django 2.2.6 on 2019-11-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0003_auto_20191129_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomiccomponent',
            name='component_factor',
            field=models.FloatField(default=0),
        ),
    ]
