# Generated by Django 2.2.5 on 2019-10-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0003_atomiccomponent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicprerequisite',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
