# Generated by Django 2.2.6 on 2020-01-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0004_auto_20191129_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomiccomponent',
            name='length_on_rular_offset',
            field=models.FloatField(default=0),
        ),
    ]
