# Generated by Django 2.2.6 on 2020-01-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atomic', '0005_atomiccomponent_length_on_rular_offset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atomiccomponent',
            old_name='length_on_rular_offset',
            new_name='length_on_ruler_offset',
        ),
    ]
