# Generated by Django 2.2.6 on 2020-01-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('description_images', models.ManyToManyField(related_name='group_description_images', to='shop.URL')),
                ('illustration_images', models.ManyToManyField(related_name='group_illustration_images', to='shop.OffsetImageURL')),
                ('thumbnail_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_thumbnail_images', to='shop.URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
