# Generated by Django 2.2.4 on 2019-09-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atomiccomponent',
            old_name='quantity',
            new_name='availability',
        ),
    ]
