# Generated by Django 2.2.4 on 2019-09-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtomicRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('atomic_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='shop.AtomicComponent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlueprintRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='atomic_requirements',
            field=models.ManyToManyField(related_name='requirements', to='shop.AtomicRequirement'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='blueprint_requirements',
            field=models.ManyToManyField(related_name='requirements', to='shop.BlueprintRequirement'),
        ),
        migrations.DeleteModel(
            name='BlueprintRequirements',
        ),
        migrations.AddField(
            model_name='blueprintrequirement',
            name='blueprint_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='shop.Blueprint'),
        ),
    ]
