# Generated by Django 2.2.4 on 2019-09-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190903_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomiccomponent',
            name='part_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
