# Generated by Django 2.2.4 on 2019-09-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blueprint',
            old_name='atomic_requirements',
            new_name='atomic_prerequisites',
        ),
        migrations.RenameField(
            model_name='blueprint',
            old_name='blueprint_requirements',
            new_name='blueprint_prerequisites',
        ),
    ]
